services:
  redis-master:
    image: redis:7
    container_name: redis-master
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./redis/master/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 172.30.0.10

  redis-replica:
    image: redis:7
    container_name: redis-replica
    command: redis-server /usr/local/etc/redis/redis.conf
    depends_on:
      - redis-master
    networks:
      redis-network:
        ipv4_address: 172.30.0.11
    volumes:
      - ./redis/replica1/redis.conf:/usr/local/etc/redis/redis.conf

  redis-replica-2:
    image: redis:7
    container_name: redis-replica-2
    networks:
      redis-network:
        ipv4_address: 172.30.0.12
    depends_on:
      - redis-master
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/replica2/redis.conf:/usr/local/etc/redis/redis.conf

  sentinel1:
    image: redis:7
    container_name: sentinel1
    command: redis-sentinel /usr/local/etc/redis/sentinel1.conf
    depends_on:
      - redis-master
    networks:
      redis-network:
        ipv4_address: 172.30.0.21
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel:/usr/local/etc/redis

  sentinel2:
    image: redis:7
    container_name: sentinel2
    command: redis-sentinel /usr/local/etc/redis/sentinel2.conf
    depends_on:
      - redis-master
    networks:
      redis-network:
        ipv4_address: 172.30.0.22
    ports:
      - "26380:26379"
    volumes:
      - ./sentinel:/usr/local/etc/redis

  sentinel3:
    image: redis:7
    container_name: sentinel3
    command: redis-sentinel /usr/local/etc/redis/sentinel3.conf
    volumes:
      - ./sentinel:/usr/local/etc/redis
    depends_on:
      - redis-master
    networks:
      redis-network:
        ipv4_address: 172.30.0.23
    ports:
      - "26381:26379"

networks:
  redis-network:
    name: redis-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
